// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-rjroTk2y37tC5c0AyKmHHqOMSBMU2Y',
    appId: '1:64451944625:web:c42e9a183edbf3deb9c290',
    messagingSenderId: '64451944625',
    projectId: 'gym-management-cb5c0',
    authDomain: 'gym-management-cb5c0.firebaseapp.com',
    storageBucket: 'gym-management-cb5c0.firebasestorage.app',
    measurementId: 'G-EWHP9E8BKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQxsHMCY8o-2ed8qlZfp5G6trrNjN1NA',
    appId: '1:64451944625:android:b3f610d02a1ae9a1b9c290',
    messagingSenderId: '64451944625',
    projectId: 'gym-management-cb5c0',
    storageBucket: 'gym-management-cb5c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR6tCvvQb5yF2sFT5cp4LBe6SMOVrQPPs',
    appId: '1:64451944625:ios:b471643c2ea6292cb9c290',
    messagingSenderId: '64451944625',
    projectId: 'gym-management-cb5c0',
    storageBucket: 'gym-management-cb5c0.firebasestorage.app',
    iosBundleId: 'com.example.gymManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR6tCvvQb5yF2sFT5cp4LBe6SMOVrQPPs',
    appId: '1:64451944625:ios:b471643c2ea6292cb9c290',
    messagingSenderId: '64451944625',
    projectId: 'gym-management-cb5c0',
    storageBucket: 'gym-management-cb5c0.firebasestorage.app',
    iosBundleId: 'com.example.gymManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-rjroTk2y37tC5c0AyKmHHqOMSBMU2Y',
    appId: '1:64451944625:web:112f58867571719cb9c290',
    messagingSenderId: '64451944625',
    projectId: 'gym-management-cb5c0',
    authDomain: 'gym-management-cb5c0.firebaseapp.com',
    storageBucket: 'gym-management-cb5c0.firebasestorage.app',
    measurementId: 'G-H9K3PPNG8V',
  );
}
